### ISSUE TITLE
inline docs need to be updated

### ISSUE THREAD

**Issue by seagle0128** [jwiegley/use-package#546] opened 2017-12-05 03:17 UTC
Thanks for the active development recently!
Could you please update the inline documents for `use-package`? It seems outdated.

**Comment by jwiegley** [comment] 2017-12-05 18:13
Excellent suggestion, will do.

**Comment by skangas** [comment] 2022-11-13 18:50
A duplicate of this bug (#581) was closed as fixed, so I'm closing this too.

**Closed by skangas** 2022-11-13 18:50 UTC
Labels: docs
