### ISSUE TITLE
:pin must be used separately from :ensure for it to work

### ISSUE THREAD

**Issue by rdiaz02** [jwiegley/use-package#255] opened 2015-09-11 11:22 UTC
Using `:pin` never works for me (emcas 24.5.1) if I do something like

```
(use-package some-package
   :ensure t
   :pin melpa-stable
 )
```

I need to call use-package twice:

```
(use-package some-package
     :pin melpa-stable
 )
(use-package some-package
   :ensure t
   :pin melpa-stable
 )
```

I guess this is related to https://github.com/jwiegley/use-package/pull/238 .

The following  `.emacs` shows the problem:

```
(package-initialize nil)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
     '("melpa" . "http://melpa.milkbox.net/packages/") t)
(add-to-list 'package-archives
     '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(package-initialize nil) ;; needed?

;; Bootstrap use-package if not installed
(unless (package-installed-p 'use-package)
 (package-install 'use-package))

 (eval-when-compile
    (require 'use-package))

;; Will not use the one from melpa-stable unless you uncomment this
;; (use-package whole-line-or-region
   ;;   :pin melpa-stable
    ;;   )

(use-package whole-line-or-region
    :ensure t
    :pin melpa-stable
    :config
   (whole-line-or-region-mode) ;; makes no difference
 )
```

**Comment by rocha** [comment] 2015-09-13 14:19
I am having the same problem, here is my sample test file:

```
(require 'package)

(setq package-archives
      '(("melpa" . "http://melpa.milkbox.net/packages/")
        ("melpa-stable" . "http://stable.melpa.org/packages/")))

(package-initialize)

(unless (package-installed-p 'use-package)
  (if (null package-archive-contents)
      (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

(use-package test-simple :ensure t :pin melpa-stable)
```

**Comment by behrica** [comment] 2015-10-20 17:30
Same problem for me. I use
 use-package-always-ensure t

and I have the same problem.

```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives
	     '("SC" . "http://joseito.republika.pl/sunrise-commander/") t)
(add-to-list 'package-archives
	     '("melpa-stable" . "http://stable.melpa.org/packages/") t)


(package-initialize) 
(if (not (package-installed-p 'use-package))
    (progn
      (package-refresh-contents)
      (package-install 'use-package)))

(eval-when-compile
  (require 'use-package))
(require' diminish)
(require 'bind-key)       
```

It uses everything from melpa, instead melpa-stable

**Comment by zilti** [comment] 2015-12-03 11:31
Same problem for me, :pin doesn't work. But apparently pinning doesn't work anyway, no matter if I use it via :pin or use the `package` feature directly.

**Comment by kevinwaddle** [comment] 2015-12-03 21:58
Making sure :pin is before :ensure seems to work as advertised for me.

**Comment by kovrik** [comment] 2016-01-28 03:07
@rdiaz02 @zilti @behrica @rocha 
This should be fixed now by #302
Can you check it please?

**Comment by kevinwaddle** [comment] 2016-01-29 22:59
Doesn't seem to be working. I closed emacs deleted my elpa directory and relaunched emacs. It prefers the melpa version.

If I delete a package through *Packages* then run package-refresh-contents and then evaluate one of the use-package forms it will get the melpa-stable version.

It seems if I run package-refresh-contents after evaluating each use-package form it gets the melpa-stable :pinned version, otherwise it won't.

**Comment by npostavs** [comment] 2016-01-30 08:07
@kevinwaddle does `(advice-add 'use-package-pin-package :after #'package-read-all-archive-contents)` help? (although this probably slows things down again).

**Comment by kevinwaddle** [comment] 2016-02-01 18:10
@npostavs I had to tweak the advice-add to read... 
`(advice-add 'use-package-pin-package :after #'(lambda (of &rest args) (package-read-all-archive-contents)))`

This does seem to be helping. It is now getting the :pinned version of the package as specified, but it isn't getting the :pinned version of the dependencies for that package.

**Comment by npostavs** [comment] 2016-02-01 18:47
> it isn't getting the :pinned version of the dependencies for that package.

Hmm, since the use-package forms are all independent, if you `use-package` a package before its dependency, there's not really a way to fix that. I guess it sort of worked before because all the pinning was done at macro expand time, although even then it still wouldn't have worked if you byte compiled.

**Comment by kevinwaddle** [comment] 2016-02-02 18:39
@npostavs apparently this is a package.el issue. 

I tested using just package-install and package-pinned-packages set to '((magit . "melpa-stable")) and it does the same thing; gets magit from melpa-stable but all the dependencies from melpa.

Maybe this will get addressed in Emacs 25?

**Comment by npostavs** [comment] 2016-02-03 08:48
> Maybe this will get addressed in Emacs 25?

Only if you* address it.

---

<sub>\* I mean, not necessarily you specifically, but don't expect it to get addressed by itself.</sub>

**Comment by kevinwaddle** [comment] 2016-02-03 15:56
Yah, I hear you. It is looking like it will be addressed with the new package-archive-priorities variable that is introduced in 25. I tested with raw package.el in 25 by setting that variable with melpa-stable being set to highest priority and it worked handled got everything it could, including dependencies, from melpa-stable.

I am not sure how this will integrate with use-package and it's :pin concept though, it may allow :pin to be deprecated, which I think might be desirable from use-package development's point of view as I noticed there was some talk of splitting :pin and :ensure out of use-package all together. 

Likewise the new package-selected-packages variable might be able to deprecate or greatly simplify :ensure in use-package as well.

**Comment by npostavs** [comment] 2016-02-03 20:12
> It is looking like it will be addressed with the new package-archive-priorities variable that is introduced in 25. I tested with raw package.el in 25 by setting that variable with melpa-stable being set to highest priority and it pulled everything it could, including dependencies, from melpa-stable.

Ah, cool, wasn't aware of that one. But if you have melpa-stable set to highest priority, and you `:pin` one package to melpa, its dependencies will still be melpa-stable. Perhaps this is actually what you want, though it's the same pinning behaviour as before, just the repos have swapped places.

**Comment by kevinwaddle** [comment] 2016-02-04 17:14
Yah, I was realizing just this as I thought about it more. Now I am not so sure about the package-archive-priorities variable being the right solution here.

If packages list their own dependencies shouldn't package.el just be getting the dependency specifically listed in the package?

I will keep digging and will investigate why package.el behaves the way it does in this regard.

**Comment by npostavs** [comment] 2016-02-04 17:48
> If packages list their own dependencies shouldn't package.el just be getting the dependency specifically listed in the package?

They can only specify a minimum version, and package.el defaults (in the absence of pinning or archive priority) to getting the highest available version which is always melpa because its version "numbers" are really timestamps.

**Comment by kevinwaddle** [comment] 2016-02-04 19:22
Gotcha. I guess having melpa coexist with a melpa-stable was not foreseen and kind of broken 'by design'.

**Closed** 2017-11-30 06:07 UTC
Labels: bug, ensure
