### ISSUE TITLE
empty :bind throws error

### ISSUE THREAD

**Issue by timmli** [jwiegley/use-package#431] opened 2017-02-17 08:17 UTC
Since a recent update of use-package, my config doesn't load anymore when `:bind` is empty, for example:
```lisp
  (use-package org
    :config
    (progn
      ;; config stuff
      )
    :bind
    )
```

This leads to the following error:
```
error: use-package: :bind a (<string or vector> . <symbol or string>) or list of these
```

It took me some time to figure out what the problem is. Maybe you could make `use-package` act more gracefully again?

**Comment by drot** [comment] 2017-02-17 11:47
Why not just use `:defer`? Also you don't need to wrap the config with `progn`, `use-package` will do that for you if it's missing.

**Comment by timmli** [comment] 2017-02-17 13:12
@drot Thanks for your hint! I know it's a stupid example and could be actually removed altogether. But, for some reason, this was left in my init file and suddently started to be problem.

**Comment by npostavs** [comment] 2017-02-17 13:25
I think it could be fixed with
```diff
--- i/use-package.el
+++ w/use-package.el
@@ -819,7 +819,7 @@ (defun use-package-normalize-pairs
 (defun use-package-normalize-binder (name keyword args)
   (use-package-as-one (symbol-name keyword) args
     (lambda (label arg)
-      (unless (consp arg)
+      (unless (listp arg)
         (use-package-error
          (concat label " a (<string or vector> . <symbol or string>)"
                  " or list of these")))
```

**Comment by sjLambda** [comment] 2017-02-17 18:04
Yes a blank bind or rem'ed out section causes this error. We need use-package to ignore such errors as we commonly use comment and uncomment settings as needed. Allow :bind section there even if there are no active bindings.

**Comment by jwiegley** [comment] 2017-02-17 18:10
This is intended behavior: `use-package` tries to tell you when your declaration is doing something that makes no sense, and having a `:bind` declaration with no bindings applies.  If you explicitly want that, then `:bind ()` should work, but I'd rather have cases like this be an error, than to just ignore them. That's why ever keyword goes through a "normalization" process before being acted on, just to catch init file problems like this.

**Closed by jwiegley** 2017-02-17 18:10 UTC

**Comment by npostavs** [comment] 2017-02-17 18:36
> If you explicitly want that, then `:bind ()` should work,

Actually, it doesn't work. I'm not sure which part normalizes that, but `(use-package ... :bind ())` and `(use-package ... :bind)` are already the same by the time we reach `use-package-normalize-binder`. Replacing `consp` with `listp` as I suggested above lets both succeed. Should I make a PR with that change?

**Comment by jwiegley** [comment] 2017-02-17 18:41
No, I'm not sure I want that, because it would allow things that make no sense, like `:bind "M-x"`. The user should be told that this is an error.

What is the use case for an empty `:bind`?  If you're commenting things out, why not comment out the keyword as well?

**Comment by npostavs** [comment] 2017-02-17 18:51
> it would allow things that make no sense, like `:bind "M-x"`

No, that remains an error because it doesn't satisfy `listp`.

> What is the use case for an empty `:bind`? If you're commenting things out, why not comment out the keyword as well?

I don't see a use case for it either, but since you mentioned `:bind ()` I thought you might want to support it.

**Comment by timmli** [comment] 2017-02-17 19:20
The question shouldn't be "does it make sense", but "does it do any harm". I don't see why empty `:bind` should be more of a problem now than it used to be. In general, getting error messages for code that had been passing checks in the past feels odd -- even if the code is silly.

**Comment by jwiegley** [comment] 2017-02-17 19:48
It was an oversight that it wasn't raising an error before.
