### ISSUE TITLE
use-package macro docstring missing some keywords

### ISSUE THREAD

**Issue by doolio** [jwiegley/use-package#581] opened 2017-12-08 17:20 UTC
Namely, `:requires`, `:when`, `:unless`, `:no-require`, `:catch`, `:hook` and `:load`.

**Comment by jwiegley** [comment] 2017-12-08 19:02
Thanks, this is a duplicate of #546.

**Closed by jwiegley** 2017-12-08 19:02 UTC

**Comment by doolio** [comment] 2017-12-08 20:31
Ah, so inline docs mean the docstring - TIL. Sorry for the noise.
