### ISSUE TITLE
"Keyword handler not defined: use-package-handler/:bind" error

### ISSUE THREAD

**Issue by lbsx** [jwiegley/use-package#553] opened 2017-12-05 07:34 UTC
Hi, I've upgrade to 20171204.1703 version, and encountered the following error when starting emacs. And all the key bindings specified in the `:bind` sections are invalid.

I'm using emacs 25.1.1 from the official debian repo. I'd like to provide additional information if needed.

```
Error (use-package): Failed to parse package neotree: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package bm: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package ibuffer: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package org: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package mu4e: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package helm-mu: use-package: Keyword handler not defined: use-package-handler/:bind
Warning (use-package): Unrecognized keyword: :ensure
Error (use-package): Failed to parse package ace-window: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package avy: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package goto-chg: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package highlight-symbol: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package ivy: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package counsel: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package magit: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package helm-gtags: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package gdb-mi: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package company: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package helm-c-yasnippet: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package irfc: use-package: Keyword handler not defined: use-package-handler/:bind
Warning (use-package): Unrecognized keyword: :ensure
Error (use-package): Failed to parse package helm-config: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package helm-swoop: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package projectile: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package expand-region: use-package: Keyword handler not defined: use-package-handler/:bind
```

**Comment by nickmccurdy** [comment] 2017-12-05 07:45
For `:ensure`, see https://github.com/melpa/melpa/pull/5167#issuecomment-349214878:

> Try adding `(eval-when-compile (require 'use-package))` after `(package-install 'use-package)` like in my previous comment. It fixed it for me, but I don't know why.

I'm not positive the `:bind` warning is caused by this but if you try it, please let me know what happens.

**Comment by lbsx** [comment] 2017-12-05 07:59
Thanks for your help. After adding `(eval-when-compile (require 'use-package))`, everything works fine.

**Comment by nickmccurdy** [comment] 2017-12-05 08:05
Cool, please close this

**Closed** 2017-12-05 09:22 UTC

**Comment by jwiegley** [comment] 2017-12-05 23:14
All helper functions now have autoload cookies, so this should be fixed without needing to require, if you use `package.el` or another package manager that loads such cookies for you.

**Comment by lbsx** [comment] 2017-12-06 04:56
Yes. I tried the latest package. It works without the `require` statement.

**Comment by nickmccurdy** [comment] 2017-12-06 16:36
Can confirm that with the latest use-package (MELPA) this works without a require, thanks for the fix!

**Comment by unhammer** [comment] 2025-08-18 12:36
for future web searchers, I saw this with

` ■  Error (use-package): Failed to parse package haskell-mode: use-package: Keyword handler not defined: use-package-handler/:pin`
(not `:bind`)

and solved it as above, by putting `(eval-when-compile (require 'use-package))` into early-init.el
