### ISSUE TITLE
Use `emacs` as a dummy feature name to call `use-package`.

### ISSUE THREAD

**Issue by hongyi-zhao** [jwiegley/use-package#948] opened 2021-08-09 06:53 UTC
I've tried the following configuration and it really works:

```emacs-lisp
(use-package emacs :config (defalias 'yes-or-no-p 'y-or-n-p))
```
So, it seems that `emacs` can be used as a dummy [named feature](https://www.gnu.org/software/emacs/manual/html_node/elisp/Named-Features.html) when calling `use-package`.

Am I right?

Regards,
HY

**Comment by rprimus** [comment] 2021-08-09 07:44
Mon Aug  9 08:35:10 BST 2021

Hi,

If you query the variable `features` in a fresh emacs, you'll see that the first defined named feature is `emacs`:

``` shell
emacs -nw -Q -eval "(describe-variable 'features)"
```

It was first mentioned in: 
```
src/ChangeLog.10:7732:	* fns.c (syms_of_fns): Add `emacs' to features.
```

**Comment by hongyi-zhao** [comment] 2021-08-10 00:51
> If you query the variable `features` in a fresh emacs, you'll see that the first defined named feature is `emacs`:

I checked with `$ emacs -Q -eval "(describe-variable 'features)"`, and find that it's the last defined named feature:

![image](https://user-images.githubusercontent.com/11155854/128791863-181933d5-deef-4576-ad9e-09e2ed482513.png)

**Comment by Mihara** [comment] 2022-02-05 20:00
And yet, `use-package-lint` complains that `emacs` module cannot be located.

**Comment by skangas** [comment] 2022-11-16 17:40
> And yet, `use-package-lint` complains that `emacs` module cannot be located.

I can't reproduce this using:

```
(use-package emacs)
```

And then `M-x use-package-lint`. Could you give more details about where you're seeing this?

**Comment by skangas** [comment] 2022-12-09 05:46
More information was requested, but none was provided within 23 days. I also can't reproduce the issue, so I'm closing it now. If this is still an issue, please report back and we can reopen. Thanks.

**Closed by skangas** 2022-12-09 05:46 UTC
Labels: moreinfo
