### ISSUE TITLE
is there any method to `exclude` ?

### ISSUE THREAD

**Issue by nesteiner** [jwiegley/use-package#946] opened 2021-07-25 13:02 UTC
there is a conflict between a configure and web-mode keymap,  
```emacs-lisp
(use-package awesome-pair
  :load-path "~/workspace/repo/awesome-pair/"
  :hook (prog-mode . awesome-pair-mode)
  :bind (:map awesome-pair-mode-map
	      ("(" . awesome-pair-open-round)
	      ("[" . awesome-pair-open-bracket)
	      ("{" . awesome-pair-open-curly)
	      (")" . awesome-pair-close-round)
	      ("]" . awesome-pair-close-bracket)
	      ("}" . awesome-pair-close-curly)))
```  

so I want to load this plugin when detecting `web-mode` not on, how can I do that

**Comment by alphapapa** [comment] 2021-07-25 14:13
Since this is not a bug report, please use an appropriate forum for questions, such as https://old.reddit.com/r/emacs

**Comment by skangas** [comment] 2022-11-13 19:14
I also suggest taking this support question to an external forum. Closing.

**Closed by skangas** 2022-11-13 19:14 UTC
Labels: question
