### ISSUE TITLE
Is :custom capable of setting minor-mode variables, or is it more limited than customization menu? 

### ISSUE THREAD

**Issue by jkroes** [jwiegley/use-package#856] opened 2020-07-18 05:45 UTC
I noted  that which-key doesn't seem to activate at all if I include the minor mode variable (which-key-mode) in `:custom`. If I call `which-key-mode` twice in succession, only now does which-key's popup activate. This issue arises with `:custom (which-key-mode t)`; however, it doesn't arise if I use `:config (which-key-mode t)`. 

I'm guessing that minor-mode variables can be set via customization menu but not `:custom`? I had assumed the keyword was able to set the values of everything the customization menu could. Is it limited to variables and options?

**Comment by jkroes** [comment] 2020-07-18 05:50
On second thought, I need to do more testing. Closing.

**Comment by jkroes** [comment] 2020-07-18 06:04
I did some more testing, and the issue seems broader than anticipated. I noted earlier that which-key doesn't seem to activate at all. When I check the value of `which-key-mode` on startup, `describe-variable` indicates that it's enabled. If I call `which-key-mode` twice in succession, the value remains the same (enabled), but only now does which-key's popup activate. This issue arises with `:custom (which-key-mode t)`; however, it doesn't arise if I use `:config (which-key-mode t)`. I also tested various values: `t`, `1` and no value to confirm the value pulled from my customization file wasn't the issue.

**Comment by a13** [comment] 2020-07-28 07:32
What Emacs version are you using? It worked well on 26.3 for me

**Comment by jkroes** [comment] 2020-08-06 00:58
I'm using Version 27.0.91.

**Comment by a13** [comment] 2020-08-19 08:37
it looks like it was broken in #850

**Comment by sirikid** [comment] 2020-08-19 08:53
Yep. Here is an example of use-package expansion. As you can see, `custom-set` property is accessed before the variable is defined and use-package always fallbacks to `set-default`.
```elisp
;; (use-package delsel
;;   :custom (delete-selection-mode t))
(progn
  (defvar use-package--warning69
    #'(lambda
        (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'delsel keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (progn
        (funcall
         (or
          (get 'delete-selection-mode 'custom-set)
          #'set-default)
         'delete-selection-mode t)
        (if
            (not
             (require 'delsel nil t))
            (display-warning 'use-package
                             (format "Cannot load %s" 'delsel)
                             :error)))
    (error
     (funcall use-package--warning69 :catch err))))
```

**Comment by a13** [comment] 2020-08-24 13:13
> * We could call `customize-set-variable` for any variable name ending with `-mode` (reverting to the old behavior)
> * We could call `custom-load-symbol` for any variable name ending with `-mode` (using the native `custom.el` code to load dependencies)

TMO both are ugly too, in theory an (abnormal?) minor mode which doesn't end with the suffix can exist as well

**Comment by a13** [comment] 2020-08-30 07:14
@conao3 The thing is minor modes are defcustoms,  so `:custom` should work for them

**Comment by a13** [comment] 2020-08-30 07:19
@tzz How about adding a function which mimics `customize-set-variable`, but doesn't save customizations into `custom-file`?

**Comment by conao3** [comment] 2020-08-30 07:35
> @conao3 The thing is minor modes are defcustoms, so :custom should work for them

I know what define-minor-mode does. And I know what define-minor-mode actually does.
But, in principle, there can be minor modes that are not defined in define-minor-mode, can't there?
And since it's true that there was a minor mode that couldn't be enabled in :custom, I added a dedicated keyword in leaf.

> @tzz How about adding a function which mimics customize-set-variable, but doesn't save customizations into custom-file?

This is not for me, but I want to comment.
This is a good idea that essentially solves this problem. I'll send this function to ML.

**Comment by a13** [comment] 2020-08-31 06:34
> But, in principle, there can be minor modes that are not defined in define-minor-mode, can't there?

They can exist but I don't think it's a good idea

**Comment by evelineraine** [comment] 2020-09-04 16:21
As far as I understand this, reason minor mode is not enabled by using `:custom` now is the change to `set-default` from `customize-set-variable`.

`define-minor-mode` expansion includes `defcustom` macro for mode's varaible with `:initialize` function set to `custom-initialize-default`. This is the case, I checked, for `which-key-mode`.

`custom-initialize-default` is one of default `custom.el` initializers _specifically_ intended for minor modes. It's designed so that `:set` function (which enables/disables mode) is not called for pre-set values (like those set with `set-default`). But whenever the varaible is set via Customize (e.g. via direct call to `customize-set-variable`), the setter is called and the mode is enabled.
See [elisp#Variable Definitions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Variable-Definitions.html) for a section about this initializer.

 Enabling minor modes also works if set in a Custom theme (like in the `user` theme stored in `custom-file`). Though I haven't been able yet to trace the exact code that calls setter for minor modes in `custom.el`, it does work.

I have written and use my tiny [evelineraine/init-custom.el](https://git.sr.ht/~evelineraine/init-custom.el) package that aggregates all settings to customizable variables in `init.el` and then runs them through `custom-theme-set-variables` code as setitngs of a single Custom theme.

The way I use it is:
```elisp
(use-package PACKAGE
  :defer t
  :init
  ; VAR can be a -mode variable
  (init-custom-set 'VAR VALUE))

;; at the bottom of init.el
(load-theme 'init-custom :no-confirm)
```

By doing customizations this way, any and all obscure Custom features work (setters, ordering, dependencies, /and/ enabling minor modes), but values can be set from anywhere in init file and nothing seems to be saved to `custom-file`.
Have a look at my code if this approach looks interesting.

I am thinking about adding an `:init-custom` keyword to `use-package` so it can be uses just like `:custom` keyword.

**Comment by a13** [comment] 2020-09-05 22:56
> I am thinking about adding an :init-custom keyword to use-package so it can be uses just like :custom keyword.

why are you trying to invent new keywords instead of reverting to the old working behavior?

**Comment by evelineraine** [comment] 2020-09-06 07:39
> why are you trying to invent new keywords instead of reverting to the old working behavior?
1. the old `customize-set-variable` wasn't working well enough, hence the move to `set-default` instead.
2. use-package is extensible via adding support for new keywords. So far I haven't considered suggesting my approach as the replacement of `:custom` implementation to the upstream.

In my opinion `customize-set-variable` isn't the right approach because:
1. It marks the symbol as customize-but-unsaved (by storing the value in `customized-value`). Any time `custom-save-variables` is called (and Emacs carelessly calls it in a lot of places, e. g. from `package.el` when installing / removing packages), all these settings are written to the `custom-file`.
This creates clutter and redundancy, but also leads to unexpected behavior: remove customization from `init.el`, but it would still be installed via `custom-file`.
2. Due to how underdeveloped `custom.el` is (IMO), there is only one fully supported way to install customizations - via themes (`custom-theme-set-variables` or `custom-set-variables` for `user` theme). Except `custom-set-variables` doesn't do type-checking, but that was intentional.
`customize-set-variables` seems only intened for interactive use, as a setter-aware version of `set-variable` minus type-checking (no good reason for that). It doesn't support theme precedence, undoing customizations, ordering via `:set-after`, deferred evaluation, and something else maybe.

To me: `custom-theme-set-variables` > `set-default` > `customize-set-variable`, so reverting back would be worse.

**Comment by a13** [comment] 2020-09-07 13:04
> the old customize-set-variable wasn't working well enough

It had worked for me for years, any example of invalid behavior? 

> all these settings are written to the custom-file.

any reason to use both `:custom` and `custom-file`?

> custom-theme-set-variables > set-default > customize-set-variable

```gz
(defun custom-set-variables (&rest args)
;; ...
  (apply 'custom-theme-set-variables 'user args))
```

**Comment by benley** [comment] 2020-09-18 19:08
A significant chunk of my emacs config stopped working now that I've got a version of use-package with #850 present.  Are there plans to get the old behavior back (or something close to it), or should I rework my config to avoid depending on defcustom behaviors?  Or is there another reasonable workaround?

**Comment by tzz** [comment] 2020-11-08 15:24
Please see #881 for an attempt to resolve this issue. Thanks to everyone who chimed in, and apologies for the late followup.

@jkroes if you want provide a test to ensure minor mode vars behave properly, that would be really terrific.

@benley I think you may be commenting on something other than this particular bug report?

> A significant chunk of my emacs config stopped working now that I've got a version of use-package with #850 present. Are there plans to get the old behavior back (or something close to it), or should I rework my config to avoid depending on defcustom behaviors? Or is there another reasonable workaround?

I'll do my best to address your issues, but would appreciate more detail than "stopped working." If you're just confirming someone else's report, you can say that or react to their report.

**Comment by benley** [comment] 2020-11-09 18:36
Ah, sorry - I commented on this issue before I really understood what was happening, and I've since found workarounds for my own needs.  My problem was indeed about setting minor-mode variables with `:custom`, and I've switched to using `:config (customize-set-variable ....)` to handle those for now.

**Comment by tzz** [comment] 2020-11-29 15:00
#881 switches to the `custom-theme-set-variables` approach which should address this issue as well. Please test and update. Thank you.

**Comment by tzz** [comment] 2020-11-29 15:03
Also @a13 and everyone else commenting here, I think a test that verifies correct behavior would be quite welcome and provide some assurance that the code won't break user expectations in the future.

**Comment by tzz** [comment] 2021-01-07 09:43
#881 has been merged, I'd like to close this issue if anyone can independently confirm and ideally provide a test for it.

**Comment by skangas** [comment] 2022-11-13 20:06
> #881 has been merged, I'd like to close this issue if anyone can independently confirm and ideally provide a test for it.

Thanks, closing.

**Closed by skangas** 2022-11-13 20:06 UTC
