### ISSUE TITLE
:if does not work with display-graphic-p predicate

### ISSUE THREAD

**Issue by doolio** [jwiegley/use-package#819] opened 2020-03-01 12:41 UTC
The following form works as expected.
```
(use-package hl-line                    ; Highlight the current line
  :if (window-system)                   ; ":if window-system" works too
  :hook ((dired-mode ibuffer-mode prog-mode) . hl-line-mode))
```
but the following does not
```
(use-package hl-line                    ; Highlight the current line
  :if (display-graphic-p)               ; ":if display-graphic-p" causes an error
  :hook ((dired-mode ibuffer-mode prog-mode) . hl-line-mode))
```
The manual recommends to use `display-graphic-p` over `window-system` but I don't understand why the second form does not work. Maybe related to (closed) issue #44.

**Comment by conao3** [comment] 2020-03-01 14:26
> The manual recommends to use display-graphic-p over window-system

Where recommends to use `display-graphic-p`?

And what errors/warnings you see related to this `use-package` block?

**Comment by doolio** [comment] 2020-03-01 14:44
> Where recommends to use display-graphic-p?

The [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-Systems.html) not the `use-package` manual. In fact, the [README](https://github.com/jwiegley/use-package#conditional-loading) uses `window-system` in an example form.

> And what errors/warnings you see related to this use-package block?

I see no errors/warnings. That is what confuses me. The form seems valid to me. However, the current line is not highlighted for me in the respective buffers. Thanks for your time.

**Comment by conao3** [comment] 2020-03-01 15:06
hmm, I understand `use-package` is just a configuration macro.
So if you face something wrong, expand issued `use-pacakge` block.
Below code is result (with [ppp](https://github.com/conao3/ppp.el))

```emacs-lisp
(setq use-package-expand-minimally t)
;;=> t

(ppp-macroexpand
 (use-package hl-line                    ; Highlight the current line
   :if (window-system)                   ; ":if window-system" works too
   :hook ((dired-mode ibuffer-mode prog-mode) . hl-line-mode)))
;;=> (when (window-system)
;;     (unless (fboundp 'hl-line-mode)
;;       (autoload #'hl-line-mode "hl-line" nil t))
;;     (add-hook 'dired-mode-hook #'hl-line-mode)
;;     (add-hook 'ibuffer-mode-hook #'hl-line-mode)
;;     (add-hook 'prog-mode-hook #'hl-line-mode))

(ppp-macroexpand
 (use-package hl-line                    ; Highlight the current line
   :if (display-graphic-p)               ; ":if display-graphic-p" causes an error
   :hook ((dired-mode ibuffer-mode prog-mode) . hl-line-mode)))
;;=> (when (display-graphic-p)
;;     (unless (fboundp 'hl-line-mode)
;;       (autoload #'hl-line-mode "hl-line" nil t))
;;     (add-hook 'dired-mode-hook #'hl-line-mode)
;;     (add-hook 'ibuffer-mode-hook #'hl-line-mode)
;;     (add-hook 'prog-mode-hook #'hl-line-mode))
```
Both expansion form is fine I think. The issue is regeneratable with `emacs -q`?

**Comment by doolio** [comment] 2020-03-07 19:17
Yes, I get the same expanded forms as you. I use [joddie/macrostep](https://github.com/joddie/macrostep) and was not aware of your ppp package so thank you. I'm currently playing around with [EXWM](https://github.com/ch11ng/exwm) and so launch an Emacs frame immediately at login so have to figure out to run `emacs -q` - perhaps I can launch Emacs inside Emacs :/. Anyway thanks for your help.

**Comment by skangas** [comment] 2022-11-29 22:06
There is some subtleties involved with `(window-system)` and `(display-graphic-p)`, but the `use-package` declaration seems fine. So this does not like a bug in use-package, and I'm therefore closing this issue now. Please report back if you disagree, and we can consider reopening.

Thanks.

**Comment by doolio** [comment] 2022-11-30 08:30
I'm fine with this issue being closed but if the goal is to include `use-package` in Emacs then shouldn't it follow the recommendation in the Emacs manual ([linked above](https://github.com/jwiegley/use-package/issues/819#issuecomment-593105009)) to use `display-graphic-p` rather than `window-system`. If it helps the following works for me:

```emacs-lisp
(use-package modus-themes
  :bind ("<f5>" . modus-themes-toggle)
  :init (modus-themes-load-themes)
  :hook (server-after-make-frame-hook . modus-themes-load-operandi)
  :config
  (if (display-graphic-p)
      (modus-themes-load-operandi)
    (modus-themes-load-vivendi)))

(use-package diff-hl                    ; Highlight hunks in fringe.
  :hook
  (;; Highlight changed files in the fringe of Dired.
   (dired-mode-hook . diff-hl-dired-mode)
   ;; Refresh diff-hl after Magit operations.
   (magit-post-refresh-hook . diff-hl-magit-post-refresh))
  :config
  ;; Highlight changes to the current file in the fringe.
  (global-diff-hl-mode)
  ;; Fall back to the display margin, if the fringe is unavailable.
  (unless (display-graphic-p)
    (diff-hl-margin-mode)))
```

**Comment by skangas** [comment] 2022-11-30 14:19
> I'm fine with this issue being closed but if the goal is to include `use-package` in Emacs then shouldn't it follow the recommendation in the Emacs manual ([linked above](https://github.com/jwiegley/use-package/issues/819#issuecomment-593105009)) to use `display-graphic-p` rather than `window-system`.

Sorry, I missed that the recommendation in the `use-package` documentation differs from the one in the Emacs manual. I've now reopened this as a documentation bug so that we can look into this.

**Comment by skangas** [comment] 2022-12-09 00:25
This has been fixed in the new use-package manual, now merged into Emacs itself: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=98e54f597e11fa760553bf7b12d8ebb388b5a488

I'm therefore closing this issue.

**Closed** 2022-12-09 00:25 UTC
Labels: confirm, docs
