### ISSUE TITLE
Calling use-package multiple times on the same package

### ISSUE THREAD

**Issue by wagk** [jwiegley/use-package#662] opened 2018-03-26 14:18 UTC
After some testing, I'm currently running under the assumption that yes, you can call `use-package` multiple times on a single package.

However, it would be nice to get some confirmation as well; Is it possible to call `use-package` multiple times on a single package? Are there any caveats that I should be looking out for when doing this?

**Comment by npostavs** [comment] 2018-03-26 14:26
> Are there any caveats that I should be looking out for when doing this?

The old `:config` block is not replaced (assuming there is deferred loading). For example,

```elisp
(use-package 'foo
   :defer t
   :config (message "configuring foo"))
(use-package 'fooAre there any caveats that I should be looking out for when doing this?
   :defer t
   :config (message "configuring foo again"))
(require 'foo)
```
would print both `configuring foo` and `configuring foo again`. This may or may not be what you want. If you're changing a `use-package` form and then re-evaluating it, it's likely not what you want.

**Comment by Wagk** [comment] 2018-03-26 14:39
I'm currently in the process of migrating my configuration into an `.org` file, leaving behind a small `.el` file to bootstrap the environment needed for the rest of the configuration.

Within the bootstrap file I would like to define core features I'll need (things like a tiny `evil` config and a very basic `helm` config) while leaving the more heavyweight configurations in the org file, explaining why I would potentially want to call `use-package` more than once per init.

I assume the chained `:config` blocks are called in order when the package loads?

**Comment by npostavs** [comment] 2018-03-26 15:00
> I assume the chained :config blocks are called in order when the package loads?

Yes, I think so.

**Comment by zzamboni** [comment] 2018-04-16 13:30
@Wagk FWIW, you can also use org-mode's [noweb features](https://orgmode.org/manual/Noweb-reference-syntax.html) to bring together multiple snippets into the corresponding section of the `use-package` declaration. You can see what I mean in my `init.org`: https://github.com/zzamboni/dot-emacs/blob/master/init.org#org-mode

If you look at the raw org file, you'll see that many of the src blocks are labeled with the `:noweb-ref` header to indicate the section under the main `use-package org` statement where they need to be placed.

**Comment by zzamboni** [comment] 2018-04-16 19:59
Glad you found it neat! My first attempt at literate programming was in fact using [noweb](https://en.wikipedia.org/wiki/Noweb) many years ago, so I found it nice that org-mode supports it too. I think it's nice, although I wish there were better support to indicate the block name/noweb-ref when exporting. As it stands, I think the unnamed blocks can be confusing. There was a question about this recently in the org-mode mailing list, and I learned that you can [customize `org-babel-exp-code-template`](https://github.com/zzamboni/dot-emacs/blob/master/init.org#cheatsheet-and-experiments) to achieve a similar effect, but that approach doesn't work for `:noweb-ref` (only for `#+NAME`), so I'm still playing with it.

**Comment by TLATER** [comment] 2019-09-06 15:10
Just to provide another use case; I like setting up built-in packages with use-package. When setting up gnus, I want to add another mail source on my work machine in a block somewhat like this:

```elisp
(cond ((string-equal (system-name) "work")
           (progn
             (add-to-list 'gnus-secondary-select-methods '(nnimap "Work"...)))
```

**Comment by mankoff** [comment] 2020-06-13 15:41
I've run into an issue with multiple calls to `use-package`.

If package `A` is loaded multiple times, and package `B` has an `:after A`, then `B` may load after the first `A` load, even if it depends on features set in subsequent `A` loads. I solved this by setting an explicit and long `defer` option for `B`, but that fix has its own drawbacks.

I'm going to solve this by having only one `use-package` call per package, and making use of `<<noweb>>` blocks.

**Comment by skangas** [comment] 2022-11-29 23:38
It seems like all questions here were resolved, so I'm closing this issue now. Please report back if I missed something.

**Closed by skangas** 2022-11-29 23:38 UTC
Labels: question

**Comment by josephtesfaye** [comment] 2025-02-27 01:20
I hope there is a section in the use-package manual addressing the usage of multiple declarations for the same package because there's often an unexpected behavior and it's really confusing to get it right.
