### ISSUE TITLE
`:diminish` stopped working

### ISSUE THREAD

**Issue by joostkremers** [jwiegley/use-package#429] opened 2017-02-13 13:35 UTC
I've been using the `:diminish` keyword extensively to get rid of minor-mode indicators, which has been working fine, but since the last update, `:diminish` seems to have issues. If I evaluate a `use-package` declaration with `C-M-x`, it works, but when I start Emacs, `:diminish` seems to be ignored.

I haven't changed anything in my Emacs config the past few days, other than updating my packages. Could it be that the latest changes in `use-package` caused `:diminish` to be ignored, or should I be looking for something in my setup? In the latter case, some hints where I could start debugging this would be very much appreciated.

**Comment by drot** [comment] 2017-02-13 14:39
Can confirm this and it only happens if you use it in conjunction with `:ensure`, then you have to have `:diminish` as the last keyword in order for it to work.

**Comment by gongzhitaao** [comment] 2017-02-13 16:16
For me it happens whatsoever unless you put it last.  For example

The following code **works** for me:

```emacs-lisp
(use-package which-key
  :config (which-key-mode)
  :diminish which-key-mode)
```

But the following code **does not** work for me

```emacs-lisp
(use-package which-key
  :diminish which-key-mode
  :config (which-key-mode))
```

**Comment by jwiegley** [comment] 2017-02-13 18:03
Was this caused by 9a4e5cbe3601361188a71bc37284af6e4adb68cc?

**Comment by dakrone** [comment] 2017-02-13 18:24
> Was this caused by 9a4e5cb?

That is what it looks like. I updated `use-package` this morning and am running into this same problem.

**Comment by jwiegley** [comment] 2017-02-13 18:35
I've reverted that commit for the time being.

**Comment by jwiegley** [comment] 2017-02-13 21:45
Should be fixed now.

**Closed by jwiegley** 2017-02-13 21:45 UTC

**Comment by joostkremers** [comment] 2017-02-13 21:57
:thumbsup:
